export enum ShapeIndex {
  RECTANGULAR = "Rectangular",
  HOLLOW_RECTANGULAR = "Hollow Rectangular",
  CIRCULAR = "Circular",
  HOLLOW_CIRCULAR = "Hollow Circular",
  I_SHAPE = "I Shape",
  T_SHAPE = "T Shape",
  ANGLE = "Angle",
  DOUBLE_ANGLE = "Double Angle",
  LIPPED_ANGLE = "Lipped Angle",
  CHANNEL = "Channel",
  DOUBLE_CHANNEL = "Double Channel",
  LIPPED_CHANNEL = "Lipped Channel",
  LIPPED_CHANNEL_SINGLE_LIP = "Lipped Channel Single Lip",
  DOUBLE_LIPPED_CHANNEL = "Double Lipped Channel",
  LIPPED_CHANNEL_BOX = "Lipped Channel Box",
  TRIANGULAR = "Triangular",
  HOLLOW_TRIANGULAR = "Hollow Triangular",
  BOX_GIRDER = "Box Girder",
  Z_SHAPE = "Z Shape",
  LIPPED_Z_SHAPE = "Lipped Z Shape",
  HAT_SHAPE = "Hat Shape",
  BULB_FLAT = "Bulb Flat",
  TEE_RAIL = "Tee Rail",
}